# Generated by Django 4.2.6 on 2023-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_cidade_alter_perfil_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
