# Generated by Django 4.2.6 on 2023-11-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto',
            new_name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não dizer')], max_length=1, null=True),
        ),
    ]
