# Generated by Django 4.2.6 on 2023-12-04 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_alter_perfil_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.AddField(
            model_name='perfil',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não dizer')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('enviou_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_enviada', to=settings.AUTH_USER_MODEL)),
                ('recebeu_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_recebida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
