# Generated by Django 4.2.6 on 2023-12-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_perfil_telefone_perfil_funcao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='funcao',
            new_name='atribuicao',
        ),
    ]
