# Generated by Django 4.2.6 on 2023-12-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='conteudo',
            new_name='mensagem',
        ),
    ]
